# Generated by Django 3.0 on 2019-12-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_consultrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultRecord',
        ),
    ]
