# Generated by Django 2.2.7 on 2019-12-27 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
