# Generated by Django 3.0.1 on 2019-12-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_role_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='menu_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单栏编号'),
        ),
    ]
