# Generated by Django 3.0.1 on 2019-12-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_permission_menu_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pmenu_title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='父标签名称'),
        ),
    ]
